#!/bin/bash

commit_msg_file=$1

# Only validate messages for merge commits
if [[ -n $commit_msg_file && $(git rev-parse --verify HEAD^2) != "HEAD^2" ]]; then
  if ! npx commitlint -E HUSKY_GIT_PARAMS < "$commit_msg_file"; then
    echo "Commit message validation failed. Please fix the errors and try again."
    exit 1
  fi
fi
