#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

# Only validate messages for merge commits
exec < /dev/tty && git interpret-trailers --in-place --trailer "pre-merge-commit=true" --trailer "merge-message-file=.git/MERGE_MSG" --hook=prepare-commit-msg
