#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

commit_msg_file=$1

# Only validate messages for merge commits
if [[ -n $commit_msg_file && $(git rev-parse --verify HEAD^2) != "HEAD^2" ]]; then
  echo $1 | npx commitlint
fi
