name: 'Android Build'

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: 'release'
      group:
        required: false
        type: string
        default: ''
      publish:
        required: false
        type: boolean
        description: Publish to Appcenter
    secrets:
      APPCENTER_TOKEN_ANDROID:
        required: true
      ANDROID_KEYSTORE:
        required: true
      ANDROID_KEY_ALIAS:
        required: true
      ANDROID_KEYSTORE_PASSWORD:
        required: true

jobs:
  build-android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install Node modules
        run: yarn ci
      
      - name: Echo group
        run: echo ${{inputs.group}}

     