# This action will lint the PR code
name: Pull Request into Dev

on:
  pull_request:
    branches: [dev]

jobs:
  #First job
  install-and-test:
    runs-on: macos-latest

    steps:
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'
      
      - name: Echo values
        run: echo ${{ (github.head_ref == "master" || github.ref_name == "master") && "release" || "beta"}}

      - name: Install Node modules
        run: yarn ci

      - name: Linting
        run: yarn lint

      - name: Close pull request if validation fails
        if: ${{ failure() }}
        uses: peter-evans/close-pull@v2
        with:
          comment: "Sorry, this pull request cannot be merged until the validation checks pass."
