name: Pull Request into Master and Preprod

on:
  pull_request:
    branches:
      - 'master'
      - 'dev'
      - 'stag'

jobs:
  #First job
  install-and-test:
    runs-on: macos-latest

    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install Node modules
        run: yarn ci

      - name: Linting
        run: yarn lint

      - name: Close pull request on master and stag if validation fails
        if: ${{ failure() && (github.head_ref!=dev || github.ref_name!=dev) }}
        uses: peter-evans/close-pull@v2
        with:
          comment: "Sorry, this pull request cannot be merged until the validation checks pass."


