# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Stag and Production Version on Push

on:
  push:
    branches: 
      - master
      - stag
      - dev

jobs:
  versioning:
    uses: ./.github/workflows/release.yml
    with:
      tag-suffix: ${{ github.head_ref || github.ref_name }}
      release-title: ${{ github.head_ref || github.ref_name }} build
    secrets: inherit

  # Second Job
  build-and-release-android:
    needs: versioning
    uses: ./.github/workflows/build-android.yml
    with:
      environment: release
      publish: ${{ github.head_ref != 'dev' && github.ref_name !='dev' }}
    secrets: inherit

  # Third Job
  build-and-release-ios:
    needs: versioning
    uses: ./.github/workflows/build-ios.yml
    with:
      publish: ${{ github.head_ref != 'dev' && github.ref_name !='dev' }}
    secrets: inherit
